---

- name: change datetime
  hosts: all
  become: yes

  tasks:
  - name: change datetime
    timezone:
      name: Asia/Omsk
  
- name: ssh users and hist keys
  hosts: all
  become: yes

  tasks:
  - name: adding users
    user:
      name: user
      password: "123"

  - name: kluch
    authorized_key:
      user: test
      state: present
      key: "{{ lookup('124.pub', '/home/test/.ssh/id_rsa.pub') }}"