---
- name: playbook
  hosts: all
  become: yes
  
  tasks:
    - name: Changing time
      timezone:
        name: Asia/Omsk

    - name: reboot cron
      service:
        name: cron
        state: restarted
    
    - name: creating users on target
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        group: sudo
      loop:
        - name: user
          pass: "{{ '123' | password_hash('md5') }}"
        - name: user1
          pass: "{{ '456' | password_hash('md5') }}"

    - name: copying our key in new user
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '/home/test/.ssh/id_rsa.pub') }}"
      loop:
        - user
        - user1

    - name: uninstall old docker packages
      apt:
        pkg:
        - docker
        - docker-compose
        - docker-compose-v2
        - docker.io
        - docker-doc
        - podman-docker
        state: absent

    - name: update & upgrade
      apt:
        upgrade: yes
        update_cache: yes

    - name: install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - name: gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: install packages
      apt:
        name: docker-ce
        state: latest
        update_cache: true