---

- name: change datetime
  hosts: all
  become: yes

  tasks:
  - name: change datetime
    timezone:
      name: Asia/Omsk
  
- name: ssh users and hist keys
  hosts: all
  become: yes

  tasks:
  - name: adding users
    user:
      name: {{ item }}
      password: "123"
    with_items:
    - user
    - user1

  - name: kluch
    authorized_key:
      user: {{ item }}
      state: present
      key: "{{ lookup('124.pub', '/home/{{ item }}/.ssh/id_rsa.pub') }}"
    with_items:
    - user
    - user1