---
- name: playbook
  hosts: all
  become: yes
  
  tasks:
  - name: timezone
    timezone:
      name: Asia/Omsk
    shell: service cron restart
  
  - name: adding users
    user:
      name: "{{ item.name }}"
      password: "{item.pass}"
      group: sudo
      home: /bin/bash
      loop:
        - {{ name: "user", pass: "123 | b64encode" }}
        - {{ name: "user1", pass: "456 | b64encode" }}

  - name: key
    copy:
      src: "/home/test/.ssh/id_rsa.pub"
      dst: "/home/{item.name}/.ssh/"
    loop:
      - {{ name: "user" }}
      - {{ name: "user1" }}

  - name: install docker and docker-compose
    # shell: 
    # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    # - sudo add-apt-repository -u "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    apt_repo:
      repo: https://download.docker.com/linux/ubuntu
      state: present
    apt:
      update_cache: yes
      upgrade: dist
      pkg: 
        - docker
        - docker-compose
        - docker-ce
      state: present
