---
- name: playbook
  hosts: all
  become: yes
  
  tasks:
  - name: Changing time
    timezone:
      name: Asia/Omsk
    # file: #Смена таймзоны по симлинку
    #   src: /usr/share/zoneinfo/Asia/Omsk
    #   dest: /etc/localtime
    #   owner: root
    #   group: root

  - name: reboot cron
    service:
      name: cron
      state: restarted
  
  - name: creating users on target
    user:
      name: "{{ item.name }}"
      password: "{{ item.pass }}"
      group: sudo
      home: /home/"{{ item.name }}"
    loop:
      - name: user
        pass: "{{ '123' | password_hash('sha512') }}"
      - name: user1
        pass: "{{ '456' | password_hash('sha512') }}"

  - name: copying our key in new user
    copy:
      src: "/home/test/.ssh/id_rsa.pub"
      dest: /home/"{{item}}"/.ssh/id_rsa.rub 
    loop:
      - user
      - user1

  # - name: added repository #Здесь добавление репы через shell
  #   shell:
  #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #     sudo add-apt-repository -u "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

  - name: added repository
    apt_repo:
      repo: https://download.docker.com/linux/ubuntu
      state: present
  
  - name: install packages
    apt:
      update_cache: yes
      upgrade: dist
      pkg: 
        - docker-compose
        - docker-ce
      state: present