---
- name: playbook
  hosts: all
  become: yes
  
  tasks:
  - name: Changing time
    timezone:
      name: Asia/Omsk
    # file: #Смена таймзоны по симлинку
    #   src: /usr/share/zoneinfo/Asia/Omsk
    #   dest: /etc/localtime
    #   owner: root
    #   group: root

  - name: reboot cron
    service:
      name: cron
      state: restarted
  
  - name: creating users on target
    ansible.builtin.user:
      # name: user
      # password: "{{ '123' | password_hash('md5') }}"
      name: "{{ item.name }}"
      password: "{{ item.pass }}"
      group: sudo
    loop:
      - name: user
        pass: "{{ '123' | password_hash('md5') }}"
      - name: user1
        pass: "{{ '456' | password_hash('md5') }}"

  - name: copying our key in new user
    ansible.posix.authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '/home/test/.ssh/id_rsa.pub') }}"
    loop:
      - user
      - user1

  # - name: added repository #Здесь добавление репы через shell
  #   shell:
  #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #     sudo add-apt-repository -u "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

  - name: added repository
    apt_repository:
      repo: https://download.docker.com/linux/ubuntu
      state: present
  
  - name: upgrade repository
    apt:
      upgrade: dist

  - name: install packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io